<a href="https://colab.research.google.com/github/curator8/66daysofdata/blob/main/exercise_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import sys
import numpy as np 

Basic Numpy notation

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a = np.array([1,2,3,4])

In [11]:
b = np.array([5,6,7,8,9])

In [ ]:
a[0]

1

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[:2]

array([1, 2])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
b[0], b[1], b[-1]

(5, 6, 9)

In [ ]:
b[[0, 1, -1]]

array([5, 6, 9])

Array types 

In [13]:
a

array([1, 2, 3, 4])

In [9]:
a.dtype

dtype('int64')

NameError: ignored

In [12]:
b

array([5, 6, 7, 8, 9])

In [14]:
b.dtype

dtype('int64')

In [ ]:
nd sha

Dimensions shapes 

In [19]:
A = np.array([
      [1,2,3],
      [4,5,6],
      [7,8,9] 
])

In [16]:
# total size of the array above is 6 

In [20]:
A.shape 

(3, 3)

Indexing and slicing Matrices 

In [21]:
#square matrix 
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
            
])

In [22]:
A[1,1]

5

In [23]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [25]:
A[1] = np.array([10,10,10])

In [26]:
A


array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [27]:
A[2] = 99

In [28]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary Statistics

In [42]:
a = np.array([
    [1,2,3,4],
    [1,2,4,5],
    [6,7,8,9]
])

In [30]:
a.sum()

10

In [31]:
a.sum()

10

In [32]:
a.mean()

2.5

In [34]:
a.std()

1.118033988749895

In [43]:
 a.sum(axis=0)


array([ 8, 11, 15, 18])

In [44]:
a.sum(axis=1)

array([10, 12, 30])

broadcasting and vectorized operations

In [45]:
a = np.arange(4)

In [46]:
a

array([0, 1, 2, 3])

In [47]:
a + 10 

array([10, 11, 12, 13])

In [48]:
a * 10

array([ 0, 10, 20, 30])

In [49]:
a 

array([0, 1, 2, 3])

In [50]:
a += 100

In [51]:
a

array([100, 101, 102, 103])

In [52]:
l = [0, 1, 2, 3]

In [53]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [54]:
a = np.arange(4)

In [55]:
a

array([0, 1, 2, 3])

In [56]:
b = np.array([10,10,10,10])

In [57]:
b

array([10, 10, 10, 10])

In [58]:
a + b

array([10, 11, 12, 13])

In [59]:
a * b

array([ 0, 10, 20, 30])

this topic of vectorized operations is so important because of Boolean arrays

Boolean arrays (also called masks)

In [60]:
a = np.arange(4)

In [61]:
a

array([0, 1, 2, 3])

In [62]:
a[[0,-1]]

array([0, 3])

In [67]:
a[[True, False, False, True]]

array([0, 3])

we select true or false depending on whether we want to select the element or not. 

In [68]:
a >= 2

array([False, False,  True,  True])

using boolean operators allows us to take advantage of the boolean arrays

In [69]:
a[a >= 2]

array([2, 3])

the expression above can select elements of the boolean of the array by setting the condition a >= 2

In [71]:
a[a > a.mean()]

array([2, 3])

In [74]:
a[~(a > a.mean())]


array([0, 1])

not greater than the mean

In [75]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [76]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [77]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [83]:
A = np.random.randint(100, size = (3,3))

In [84]:
A

array([[65, 11, 80],
       [21, 17, 34],
       [89, 50, 97]])

In [85]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]             
])]  

array([65, 80, 17, 89, 97])

In [86]:
A > 30

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [87]:
a[(a == 0) | (a == 1)]

array([0, 1])

we can use boolean expressions for filtering purposes which is really nice for a big data set.

Linear Algebra

In [88]:
A = np.array([
      [1,2,3],
      [4,5,6],
      [7,8,9]

])

In [94]:
B = np.array([
      [6,5],
      [4,3],
      [2,1]
])

In [95]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [96]:
A @ B #cross product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [97]:
B.T #transposing

array([[6, 4, 2],
       [5, 3, 1]])

In [98]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
B.T @ A #transportion and cross product.

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

int, floats

In [100]:
sys.getsizeof(1) #total number of bytes needed for integer

28

In [101]:
sys.getsizeof(10**100)

72

In [102]:
np.dtype(int).itemsize #how many bytes it takes for numpy

8

In [103]:
np.dtype(float).itemsize

8

In [104]:
np.dtype(int).itemsize

8

In [106]:
np.dtype(np.int8).itemsize

1

Lists are even larger

In [107]:
 sys.getsizeof([1]) #a one-element list

80

In [108]:
# An array of one element in numpy

In [109]:
np.array([1]).nbytes

8

and performance is also important

In [111]:
l = list(range(100000))

In [115]:
a = np.arange(100000)

In [116]:
%time np.sum(a ** 2)

CPU times: user 2.19 ms, sys: 0 ns, total: 2.19 ms
Wall time: 1.45 ms


333328333350000

In [117]:
%time sum([x ** 2 for x in l])

CPU times: user 489 µs, sys: 0 ns, total: 489 µs
Wall time: 1.34 ms


332833500

Useful numpy functions

random

In [118]:
np.random.random(size = 2)

array([0.95640973, 0.29469385])

In [119]:
np.random.normal(size = 2)

array([0.67010703, 2.30967305])

In [120]:
np.random.rand(2, 4)

array([[0.36398332, 0.53366988, 0.03373987, 0.58009804],
       [0.2983368 , 0.70342397, 0.19186805, 0.63846921]])

arange

In [124]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [123]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape 

In [125]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [126]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [127]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [128]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [129]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [131]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [132]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [137]:
"Hello World"[6]

'W'