<a href="https://colab.research.google.com/github/curator8/66daysofdata/blob/main/exercise_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import sys
import numpy as np 

Basic Numpy notation

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a = np.array([1,2,3,4])

In [11]:
b = np.array([5,6,7,8,9])

In [ ]:
a[0]

1

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[:2]

array([1, 2])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
b[0], b[1], b[-1]

(5, 6, 9)

In [ ]:
b[[0, 1, -1]]

array([5, 6, 9])

Array types 

In [13]:
a

array([1, 2, 3, 4])

In [9]:
a.dtype

dtype('int64')

NameError: ignored

In [12]:
b

array([5, 6, 7, 8, 9])

In [14]:
b.dtype

dtype('int64')

In [ ]:
nd sha

Dimensions shapes 

In [19]:
A = np.array([
      [1,2,3],
      [4,5,6],
      [7,8,9] 
])

In [16]:
# total size of the array above is 6 

In [20]:
A.shape 

(3, 3)

Indexing and slicing Matrices 